source 'https://rubygems.org'

gem 'capybara'
gem 'webdrivers'
gem 'cucumber'
gem 'rspec'
gem 'rubocop'
gem 'selenium-webdriver'
gem 'site_prism'
gem 'headless'
gem 'namey'
gem 'pry'
gem 'rspec'
gem 'rake'
gem 'httparty'
gem 'json'